"""create canonical text foundation

Revision ID: d49034f5c5da
Revises: 
Create Date: 2026-08-18 19:39:49.794540
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd49034f5c5da'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('iso_code', sa.String(length=35), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('native_name', sa.String(length=255), nullable=True),
    sa.Column('script', sa.String(length=100), nullable=True),
    sa.Column('direction', sa.String(length=3), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.CheckConstraint("direction IN ('ltr', 'rtl')", name=op.f('ck_languages_direction')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_languages')),
    sa.UniqueConstraint('iso_code', name=op.f('uq_languages_iso_code'))
    )
    op.create_table('texts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_reference_scheme_id', sa.Uuid(), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_texts')),
    sa.UniqueConstraint('slug', name=op.f('uq_texts_slug'))
    )
    op.create_table('canonical_units',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('text_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('internal_key', sa.String(length=255), nullable=False),
    sa.Column('unit_type', sa.String(length=100), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['text_id'], ['texts.id'], name=op.f('fk_canonical_units_text_id_texts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_canonical_units')),
    sa.UniqueConstraint('text_id', 'internal_key', name=op.f('uq_canonical_units_text_id_internal_key')),
    sa.UniqueConstraint('text_id', 'ordinal', name=op.f('uq_canonical_units_text_id_ordinal'))
    )
    op.create_index(op.f('ix_canonical_units_text_id'), 'canonical_units', ['text_id'], unique=False)
    op.create_table('reference_schemes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('text_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['text_id'], ['texts.id'], name=op.f('fk_reference_schemes_text_id_texts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reference_schemes')),
    sa.UniqueConstraint('text_id', 'name', name=op.f('uq_reference_schemes_text_id_name'))
    )
    op.create_index(op.f('ix_reference_schemes_text_id'), 'reference_schemes', ['text_id'], unique=False)
    op.create_foreign_key(
        'fk_texts_default_reference_scheme_id_reference_schemes',
        'texts',
        'reference_schemes',
        ['default_reference_scheme_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.create_table('structure_nodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('text_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('node_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('short_title', sa.String(length=100), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('start_unit_ordinal', sa.Integer(), nullable=True),
    sa.Column('end_unit_ordinal', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['structure_nodes.id'], name=op.f('fk_structure_nodes_parent_id_structure_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['text_id'], ['texts.id'], name=op.f('fk_structure_nodes_text_id_texts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_structure_nodes')),
    sa.UniqueConstraint('text_id', 'parent_id', 'ordinal', name=op.f('uq_structure_nodes_text_id_parent_id_ordinal'))
    )
    op.create_index(op.f('ix_structure_nodes_parent_id'), 'structure_nodes', ['parent_id'], unique=False)
    op.create_index(op.f('ix_structure_nodes_text_id'), 'structure_nodes', ['text_id'], unique=False)
    op.create_index('ix_structure_nodes_text_id_start_end', 'structure_nodes', ['text_id', 'start_unit_ordinal', 'end_unit_ordinal'], unique=False)
    op.create_table('reference_labels',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reference_scheme_id', sa.Uuid(), nullable=False),
    sa.Column('start_unit_id', sa.Uuid(), nullable=False),
    sa.Column('end_unit_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('normalized_label', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['end_unit_id'], ['canonical_units.id'], name=op.f('fk_reference_labels_end_unit_id_canonical_units'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reference_scheme_id'], ['reference_schemes.id'], name=op.f('fk_reference_labels_reference_scheme_id_reference_schemes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['start_unit_id'], ['canonical_units.id'], name=op.f('fk_reference_labels_start_unit_id_canonical_units'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reference_labels')),
    sa.UniqueConstraint('reference_scheme_id', 'normalized_label', name=op.f('uq_reference_labels_reference_scheme_id_normalized_label'))
    )
    op.create_index(op.f('ix_reference_labels_reference_scheme_id'), 'reference_labels', ['reference_scheme_id'], unique=False)
    op.create_index('ix_reference_labels_scheme_range', 'reference_labels', ['reference_scheme_id', 'start_unit_id', 'end_unit_id'], unique=False)
    op.create_table('text_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('text_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('abbreviation', sa.String(length=50), nullable=True),
    sa.Column('default_language_id', sa.Uuid(), nullable=False),
    sa.Column('reference_scheme_id', sa.Uuid(), nullable=True),
    sa.Column('version_type', sa.String(length=100), nullable=False),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('license', sa.String(length=255), nullable=True),
    sa.Column('rights_statement', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['default_language_id'], ['languages.id'], name=op.f('fk_text_versions_default_language_id_languages'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reference_scheme_id'], ['reference_schemes.id'], name=op.f('fk_text_versions_reference_scheme_id_reference_schemes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['text_id'], ['texts.id'], name=op.f('fk_text_versions_text_id_texts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_text_versions')),
    sa.UniqueConstraint('text_id', 'slug', name=op.f('uq_text_versions_text_id_slug'))
    )
    op.create_index(op.f('ix_text_versions_text_id'), 'text_versions', ['text_id'], unique=False)
    op.create_table('preferred_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('text_id', sa.Uuid(), nullable=False),
    sa.Column('start_unit_id', sa.Uuid(), nullable=False),
    sa.Column('end_unit_id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['end_unit_id'], ['canonical_units.id'], name=op.f('fk_preferred_versions_end_unit_id_canonical_units'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['start_unit_id'], ['canonical_units.id'], name=op.f('fk_preferred_versions_start_unit_id_canonical_units'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['text_id'], ['texts.id'], name=op.f('fk_preferred_versions_text_id_texts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['text_versions.id'], name=op.f('fk_preferred_versions_version_id_text_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_preferred_versions')),
    sa.UniqueConstraint('text_id', 'start_unit_id', 'end_unit_id', 'role', 'priority', name=op.f('uq_preferred_versions_text_id_start_unit_id_end_unit_id_role_priority'))
    )
    op.create_index('ix_preferred_versions_text_role_range', 'preferred_versions', ['text_id', 'role', 'start_unit_id', 'end_unit_id'], unique=False)
    op.create_table('version_releases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('version_label', sa.String(length=255), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['text_versions.id'], name=op.f('fk_version_releases_version_id_text_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_version_releases')),
    sa.UniqueConstraint('version_id', 'version_label', name=op.f('uq_version_releases_version_id_version_label'))
    )
    op.create_index(op.f('ix_version_releases_version_id'), 'version_releases', ['version_id'], unique=False)
    op.create_index('uq_version_releases_current_version', 'version_releases', ['version_id'], unique=True, postgresql_where=sa.text('is_current'), sqlite_where=sa.text('is_current = 1'))
    op.create_table('version_segments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version_release_id', sa.Uuid(), nullable=False),
    sa.Column('language_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('text_plain', sa.Text(), nullable=False),
    sa.Column('content_markup', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('block_type', sa.String(length=100), nullable=True),
    sa.Column('source_identifier', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], name=op.f('fk_version_segments_language_id_languages'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['version_release_id'], ['version_releases.id'], name=op.f('fk_version_segments_version_release_id_version_releases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_version_segments')),
    sa.UniqueConstraint('version_release_id', 'sequence', name=op.f('uq_version_segments_version_release_id_sequence'))
    )
    op.create_index(op.f('ix_version_segments_version_release_id'), 'version_segments', ['version_release_id'], unique=False)
    op.create_table('segment_unit_mappings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('segment_id', sa.Uuid(), nullable=False),
    sa.Column('canonical_unit_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('mapping_type', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_unit_id'], ['canonical_units.id'], name=op.f('fk_segment_unit_mappings_canonical_unit_id_canonical_units'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['version_segments.id'], name=op.f('fk_segment_unit_mappings_segment_id_version_segments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_segment_unit_mappings')),
    sa.UniqueConstraint('segment_id', 'canonical_unit_id', 'sequence', name=op.f('uq_segment_unit_mappings_segment_id_canonical_unit_id_sequence'))
    )
    op.create_index(op.f('ix_segment_unit_mappings_canonical_unit_id'), 'segment_unit_mappings', ['canonical_unit_id'], unique=False)
    op.create_index(op.f('ix_segment_unit_mappings_segment_id'), 'segment_unit_mappings', ['segment_id'], unique=False)
    op.create_index('ix_segment_unit_mappings_unit_sequence', 'segment_unit_mappings', ['canonical_unit_id', 'sequence'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_segment_unit_mappings_unit_sequence', table_name='segment_unit_mappings')
    op.drop_index(op.f('ix_segment_unit_mappings_segment_id'), table_name='segment_unit_mappings')
    op.drop_index(op.f('ix_segment_unit_mappings_canonical_unit_id'), table_name='segment_unit_mappings')
    op.drop_table('segment_unit_mappings')
    op.drop_index(op.f('ix_version_segments_version_release_id'), table_name='version_segments')
    op.drop_table('version_segments')
    op.drop_index('uq_version_releases_current_version', table_name='version_releases', postgresql_where=sa.text('is_current'), sqlite_where=sa.text('is_current = 1'))
    op.drop_index(op.f('ix_version_releases_version_id'), table_name='version_releases')
    op.drop_table('version_releases')
    op.drop_index('ix_preferred_versions_text_role_range', table_name='preferred_versions')
    op.drop_table('preferred_versions')
    op.drop_index(op.f('ix_text_versions_text_id'), table_name='text_versions')
    op.drop_table('text_versions')
    op.drop_index('ix_reference_labels_scheme_range', table_name='reference_labels')
    op.drop_index(op.f('ix_reference_labels_reference_scheme_id'), table_name='reference_labels')
    op.drop_table('reference_labels')
    op.drop_index('ix_structure_nodes_text_id_start_end', table_name='structure_nodes')
    op.drop_index(op.f('ix_structure_nodes_text_id'), table_name='structure_nodes')
    op.drop_index(op.f('ix_structure_nodes_parent_id'), table_name='structure_nodes')
    op.drop_table('structure_nodes')
    op.drop_index(op.f('ix_reference_schemes_text_id'), table_name='reference_schemes')
    op.drop_constraint(
        'fk_texts_default_reference_scheme_id_reference_schemes',
        'texts',
        type_='foreignkey',
    )
    op.drop_table('reference_schemes')
    op.drop_index(op.f('ix_canonical_units_text_id'), table_name='canonical_units')
    op.drop_table('canonical_units')
    op.drop_table('texts')
    op.drop_table('languages')
    # ### end Alembic commands ###
